### ISSUE TITLE
html 转 virtual dom

### ISSUE THREAD

**Issue by forever-z-133** [foreverZ133/others#135]
```html
const html = `
  <div xxx>
    <div class="a" id="b">
      <span>x</span>
    </div>
    <img visible disable='false'/>
    x<span value="0.1">y</span>u
  </div>x
`
```
```js
function initTemplate(html, re = []) {
  html = html.replace(/[\n\t]\s*/gi, ''); // 去除换行和不必要的空格，暂不支持注释的节点

  const htmlReg2 = /<([a-z]+)([^<]+)*(?:>(.*)<\/\1>|\s*\/>)|(?!:\>)[^<]+(?!:<)/gi;
  html.replace(htmlReg2, (outerHTML, tagName, attrs, innerHTML) => {
    // 将 attrs 字符串转为对象形式
    attrs = stringToObject(attrs , ' ', ':');
    // 如果还有 innerHTML 则继续寻找子级
    const childNodes = innerHTML ? initTemplate(innerHTML, []) : [];
    // 放入父级数组之下，纯文本无 tagName
    re.push({ tagName, attrs, outerHTML, innerHTML, childNodes });
  })
  return re;
}
```

CSS 字符串转对象的正则为

```css
/**
 * 测试用例
 * 引入字体图标
 */
@font-family {
  font-family: 'xx';
  src: url() format('woff'), url();
}
.icon {
  font-family: 'xx';
  font-size: 10px;
}
/* --- 响应式 ---- */
@media (min-width: 992px) {
  .icon { font-size: 14px; }
}
```
```js
function cssStrToCssObject(cssStr) {
  cssStr = cssStr.replace(/\s*[\t\n]\s*/g, ''); // 去掉换行
  cssStr = cssStr.replace(/\/\*.*?\*\//g, ''); // 去除注释
  
  const reg = /(?<=^|}|{)\s*([^}{]*?)\s*{\s*(([^}]*?{\s*.*?})|([a-z\-]*?:.*?(?=;|}))*)\s*}/g;
  const cssObj = (function loop(str, res) {
    str.replace(reg, (match, key, attrs, child) => {
      if (child) { // @media{.b{x:1}} 形态的
        child = loop(child, []);
        attrs = void 0;
      } else if (attrs) { // .a{x:1} 形态的
        attrs = stringToObject(attrs, /\s*;\s*/, /\s*:\s*/);
      }
      res.push({ key, attrs, child });
    });
    return res;
  })(cssStr, []);

  return cssObj;
}
```

-----
其中用到的其他方法：

```js
function stringToObject(str, divide, concat) {
  if (!str || typeof str !== 'string') return {};
  divide = divide || '&';
  concat = concat || '=';
  var arr = str.split(divide);
  return arr.reduce(function (re, item) {
    if (!item) return re;
    var temp = item.split(concat);
    var key = temp.shift().trim();
    var value = temp.join(concat).trim();
    if (!key) return re;
    if (['null', 'undefined'].indexOf(value) > -1) value = undefined;
    if (value === 'true') value = true;
    if (value === 'false') value = false;
    re[key] = value;
    return re;
  }, {});
}
```
