### ISSUE TITLE
H5 适配暗黑模式

### ISSUE THREAD

**Issue by forever-z-133** [foreverZ133/others#170]
先让浏览器知道本页面两种模式都适用。
```html
<meta name="color-scheme" content="light dark">
```
```css
:root { color-scheme: light dark; }
```
然后用 `@media` 分别适配。
```css
:root {
  background: white;
  color: black;
}
@media (prefers-color-scheme: dark) {
  :root {
    background: black;
    color: white;
  }
}
```
图片则需要用 `picture` 才行。
```html
<picture>
  <source srcset="dark.jpg" media="(prefers-color-scheme: dark)" />
  <img src="light.jpg"/>
</picture>
```
js 则可用 `matchMedia` 来判断
```js
const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)');
handlerColorSchemeChange();
mediaQuery.addListener(handlerColorSchemeChange);

function handlerColorSchemeChange() {
  if (mediaQuery.matches) console.log('现在是深色模式');
  else console.log('现在是浅色模式');
}
```
