### ISSUE TITLE
使用 :after 实现换行

### ISSUE THREAD

**Issue by forever-z-133** [foreverZ133/others#172]
```html
<span>1</span><span>2</span>
```

```css
span::after { content: "\A"; white-space: pre; }
```
