### ISSUE TITLE
less 循环公共方法

### ISSUE THREAD

**Issue by forever-z-133** [foreverZ133/others#187]
```less
/* 数组的遍历，i 为索引(从1开始)，value 为项值 */
.arrayForEach(@list, @code) {
  & {
    .loop(@i: 1) when (@i =< length(@list)) {
      @value: extract(@list, @i);
      @code();
      .loop(@i + 1);
    }
    .loop();
  }
}
/* 数字的遍历，i 为索引(从1开始)，value 为 start+i-1 的值，比如 4-6，索引123，值为456 */
.numberForEach(@start, @end, @code) {
  & {
    .loop(@i: 1) when (@i =< @end - @start + 1) {
      @value: @i;
      @code();
      .loop(@i + 1);
    }
    .loop();
  }
}
```
### example: 
```less
.box { width: 20px; height: 20px }
.box.nth-child(3) { margin-bottom: 10px }

@colors: green, red, blue;
.arrayForEach(@colors, {
  .box.@{value} {
      background: @value;
    &::after {
      content: '@{i}'
    }
  }
});

.numberForEach(4, 6, {
  .box-@{i}::after {
    content: '@{value}';
  }
});
```

https://codepen.io/foreverZ133/pen/poRLRON
