### ISSUE TITLE
长宽比 aspect-ratio

### ISSUE THREAD

**Issue by forever-z-133** [foreverZ133/others#82]
等比缩放，使得只需改动宽度，高度自动变化。
以往都是用 `:before` 和 `padding-top`，缺点是子级必须绝对定位才能显示在容器中。
```css
.ratio {
  position: relative;
}
.ratio:before {
  content: "";
  padding-top: 100%;
  display: block;
}
.ratio.slide:before {
  padding-top: 56.25%;
}
.ratio > * {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
```
如果你使用的是 rem 或 vw 式的响应式布局，那也是自带等比缩放的。
```css
.item {
  width: 1rem;
  height: 1rem;
}
```
后来看到一个相当不错的 [网站](https://atomiks.github.io/30-seconds-of-css/)，里面有个更让人惊艳的实现。
但实际情况中，子级往往都与父级等大，所以这个并没有出名。
```css
.ratio:before {
  content: '';
  padding-top: 100%;
  float: left;
}
.ratio:after {
  content: '';
  display: block;
  clear: both;
}
```
然后，我发现了更多骚操作，比如 CSS 的 `aspect-ratio`，相当优美。
```css
/* 尚在标准讨论阶段，随便看看 */
.ratio {
  width: 100%;
  height: aspect-ratio(16/9);
}
.ratio {
  width: 100%;
  aspect-ratio: calc(16/9);
}
```
或者 [postcss-aspect-ratio](https://github.com/arccoza/postcss-aspect-ratio) 插件，虽然只是第一种方案的插件化。
```css
.aspect-box {
  position: relative;
  aspect-ratio: '16:9';
}
```
